XCTestHTMLReport/XCTestHTMLReport

- XCUITestHTMLReport/XCUITestHTMLReport.xcodeproj/project.pbxproj
- XCUITestHTMLReport/XCUITestHTMLReport.xcodeproj/xcshareddata/xcschemes/XCUITestHTMLReport.xcscheme
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/BackgroundColor.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/CodesParser.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/Color.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/ControlCode.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/ModesExtractor.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/OutputTarget.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/Rainbow.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/String+Rainbow.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/StringGenerator.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/Style.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Libraries/Rainbow/XcodeColorsSupport.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Logger.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/Activity.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/Argument.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/Attachment.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/Command.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/RunDestination.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/Summary.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/TargetDevice.swift
- XCUITestHTMLReport/XCUITestHTMLReport/Models/TestSummary.swift
- XCUITestHTMLReport/XCUITestHTMLReport/main.swift
Ticket: #2 
```
$ ./xchtmlreport -r TestResults -v
Parsing Test Summaries
▸ Searching for action_TestSummaries.plist in TestResults
▸ Found action_TestSummaries.plist at path: TestResults/2_Test/action_TestSummaries.plist
▸ Parsing RunDestination
▸ Parsing TargetDevice
▸ Parsing TestSummary
Parsing Activity Logs
▸ Searching for action.xcactivitylog in TestResults
▸ Found TestResults/2_Test/action.xcactivitylog at path: TestResults/2_Test/action.xcactivitylog
▸ Gunzipping activity logs
Building HTML..
▸ Writing report to TestResults/index.html
Report successfully created at TestResults/index.html
```
> Added -v argument to print more details logs

- .gitignore
- XCTestHTMLReport/XCTestHTMLReport.xcodeproj/project.pbxproj
- XCTestHTMLReport/XCTestHTMLReport.xcodeproj/xcshareddata/xcschemes/XCTestHTMLReport.xcscheme
- XCTestHTMLReport/XCTestHTMLReport/Models/Activity.swift
- XCTestHTMLReportSampleApp/XCTestHTMLReportSampleApp.xcodeproj/xcshareddata/xcschemes/XCTestHTMLReportSampleApp.xcscheme
#44 
If the code making the test fail is contained in an activity then the PR will write the activity in red
so that it's easier to find which activity is failing especially in case continueAfterFailure = true
**Screenshot**
> 44: Write activities containing a failure in red

- README.md
- xchtmlreport.rb
The formula is not submitted to the Homebrew formulas yet, so it installs via a "tap".
Here's the PR to add it to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/26977
> Add Homebrew formula

- XCTestHTMLReport/XCTestHTMLReport/Models/Run.swift
⚠️ Not ready to be merged
Fixes #56 
TODO:
> 56: failed to extract activity logs

- XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Summary.swift
**Purpose**: 
I run XCTest using Jenkins with multiple result bundles. 
I would like to get some information about summary test to mark Jenkins build FAILED or SUCCESS
I added more verbose log to print some summary information, so that Jenkins can use this information for processing.
> Add log to print summary test result

- xchtmlreport.rb
Since the main development branch is apparently develop, we should update the `head` in the Homebrew spec to point to it, as it points to master by default.
> Point Homebrew formula's `head` to develop branch

- XCTestHTMLReport/XCTestHTMLReport/Classes/HTMLTemplates.swift
- XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Attachment.swift
- XCTestHTMLReport/XCTestHTMLReport/HTML/screenshot.html
- XCTestHTMLReport/XCTestHTMLReport/HTML/text.html
https://github.com/TitouanVanBelle/XCTestHTMLReport/issues/109
Displays the name of an attachment if user have provided such. One caveat is that I haven't tested with more than screenshots so `Name.Constants` is probably missing some values 🙂 
Before
After
> Display attachment name if available

- XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Run.swift
Logs aren't working in develop. It seems the log file name doesn't match what the html points to.
Use the device's `uniqueIdentifier` instead of `identifier` in the file name of the logs txt file as this is what the HTML looks for. This seems to match the intent of the `uniqueIdentifier` property.
It could be the other way round though. Let me know if it should be and I can update.
> Ensure log filename matches generated HTML

- XCTestHTMLReport/XCTestHTMLReport.xcodeproj/project.pbxproj
The project fails to build when there is a space in the path name. Submitted this as bug #117.
> Fixing support for spaces in project path

- .travis.yml
- XCTestHTMLReport/XCTestHTMLReport.xcodeproj/project.pbxproj
Xcode 10.2 is in beta, and `xchtmlreport` built with it crashes because it can't find Swift shared libraries.
This PR fixes the runpath to look in the current toolchain for these libraries.
In addition, I've added an Xcode version matrix to include 9.3, 10.1 & 10.2.
I've also made Travis build and run `./xchtmlreport -h` to see that it can load correctly.
> Fix Xcode 10.2 build to look for Swift frameworks correctly

- XCTestHTMLReport/XCTestHTMLReport/Classes/Models/TestSummary.swift
There was a problem with TestSummary was only querying status one level deep. It looks like this was introduced when the infinite loop problem was fixed in test generation. The loop now won’t run forever, but it also won’t visit every subnode.
I added a recursive function within TestSummary. I’m wondering if in the future this recursive querying shouldn’t be added into the model layer instead. But this change should fix the issue without adding too much refactoring or risk of further issue into the project itself.
> Fixing test device status not reflecting pass

- xchtmlreport.rb
Apparently the Swift compiler doesn't like being in a double sandbox: https://github.com/yonaskolb/XcodeGen/issues/51#issuecomment-331615462
> Fix Homebrew for 2.0.0 release

- Sources/XCTestHTMLReport/Classes/HTMLTemplates.swift
- Sources/XCTestHTMLReport/Classes/Models/Activity.swift
- Sources/XCTestHTMLReport/Classes/Models/Attachment.swift
- Sources/XCTestHTMLReport/Classes/Models/RenderingContent.swift
- Sources/XCTestHTMLReport/Classes/Models/ResultFile.swift
- Sources/XCTestHTMLReport/Classes/Models/Run.swift
- Sources/XCTestHTMLReport/Classes/Models/Summary.swift
- Sources/XCTestHTMLReport/Classes/Models/Test.swift
- Sources/XCTestHTMLReport/Classes/Models/TestSummary.swift
- Sources/XCTestHTMLReport/HTML/run.html
- Sources/XCTestHTMLReport/HTML/screenshot.html
- Sources/XCTestHTMLReport/HTML/text.html
- Sources/XCTestHTMLReport/main.swift
This PR adds a CLI-option `-i Inline all assets in the resulting html-file, making it heavier, but more portable`, passing this in will inline images in the resulting `index.html`
When e.g. using this in a CI it's very useful to be able to have a single artifact that can be downloaded/stored in some way, this enables that.
We're e.g. using CircleCI, where it's possible to upload artifacts that can later be accessed as a webpage, having to upload the whole directory makes this very slow, and it also seems to occasionally drop links to images.
> Make it possible to inline assets into the resulting index.html

- Package.resolved
- Package.swift
Hi!
There was a crash in XCResultKit, you can look fix here: https://github.com/davidahouse/XCResultKit/pull/18 
Just updated package version. I've tested this solution, it works
> Fix crash in XCResultKit: XCResultKit updated

- Package.resolved
- Package.swift
Bumps XCResultKit to 0.5.7 which fixes #166.
Tested on configuration which was failing with previous v0.5.5 version of XCResultKit: 4 devices with 39 test cases = 156 test cases in total
> Update XCResultKit to 0.5.7 fixing #166

- .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
- Sources/XCTestHTMLReport/Classes/Extensions/String+Path.swift
- Sources/XCTestHTMLReport/Classes/HTMLTemplates.swift
- Sources/XCTestHTMLReport/Classes/Helpers/AttachmentHelpers.swift
- Sources/XCTestHTMLReport/Classes/Helpers/ImageHelpers.swift
- Sources/XCTestHTMLReport/Classes/Helpers/UnattachedFiles.swift
- Sources/XCTestHTMLReport/Classes/Models/Activity.swift
- Sources/XCTestHTMLReport/Classes/Models/Attachment.swift
- Sources/XCTestHTMLReport/Classes/Models/ResultFile.swift
- Sources/XCTestHTMLReport/Classes/Models/Run.swift
- Sources/XCTestHTMLReport/Classes/Models/Test.swift
- Sources/XCTestHTMLReport/Classes/Models/TestScreenshotFlow.swift
- Sources/XCTestHTMLReport/Classes/Models/TestSummary.swift
- Sources/XCTestHTMLReport/Classes/Protocols/HTML.swift
- Sources/XCTestHTMLReport/HTML/index.html
- Sources/XCTestHTMLReport/HTML/test.html
- Sources/XCTestHTMLReport/main.swift
Reimplementation of this PR https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/114 compatible with Xcode 11. issue https://github.com/TitouanVanBelle/XCTestHTMLReport/issues/105
Also added some convenience options for reducing the payload size of the results
`-z` to compress images
`-d` to delete any files that are not referenced in the HTML
Also added a screenshot tail, the last 3 failing screenshots. and screenshot flow, to display all screenshots
> Added image resizing, attachment cleanup and screenshot flows

- Sources/XCTestHTMLReportCore/Classes/Models/JUnitReport.swift
- Tests/XCTestHTMLReportTests/JUnitReportTests.swift
- Tests/XCTestHTMLReportTests/TestSupportNDHppleElement.swift
- Adds escaping for classes, functions, suites, etc in JUnit Report xml.
- Adds unit tests to prevent regressions.
- This solves #186. 
- Added tests will also prevent #131 from happening in the future.
> Escaping of class names, test names, suite names. Add tests

- README.md
- Sources/XCTestHTMLReportCore/Classes/Models/Attachment.swift
On the real device, the screenshot is captured as .heic.
> Add heic as one of the supported screenshots

- Sources/XCTestHTMLReportCore/Classes/Models/ResultFile.swift
Fix for #147, #173 , potentially #145 .
Using "Resource Root URL" on Jenkins, so no CSP changes needed
edit: changed commit
> Add ".log" extension to log filename

- .github/workflows/ci.yml
Create a basic GitHub action to build/test the primary executable against N & N-1 Xcode versions on PR/push to trunk
> GH Action for CI build

- Sources/XCTestHTMLReportCore/Classes/Models/ResultFile.swift
- Sources/XCTestHTMLReportCore/Classes/Protocols/EmittableOutput.swift
Xcode 13 began nesting emitted output under `ActivityLogUnitTestSection`
We need to print the title & emitted output, as well as any nested unit test subsections for each test.
Updated screenshot:
> Fix emitted logs for Xcode 13 output

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/sync-next.yml
Xcode 13 has been the standard for several months now - we will begin building/testing only in Xcode 13 and later update the Swift version to 5.5.
Other minor QOL changes including arm64 (Apple Silicon) release artifacts and xcpretty.
> Update actions, remove xc 12.5

- Package.swift
- Sources/XCTestHTMLReportCore/Classes/HTMLTemplates.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Attachment.swift
**Background**
Currently any attachments that don't fall into existing types (video, image, text-encoded) won't display in the report. 
Even worse, the activity will still be displayed but expanding the activity shows nothing.
**Changes**
Adding rudimentary support for "other" file type attachments
When selected, "other" file types will display a download link in the preview pane
Inline attachments are still a bit tricky since we need to know the mime type in order to encode and download. This change includes "zip" by default (per my use case).
Ultimately, `AttachmentType` should be replaced with Apple's `UTType`.
> Show download link for other attachment mime types

- Sources/XCTestHTMLReportCore/Classes/Models/ResultFile.swift
- Tests/XCTestHTMLReportTests/FunctionalTests.swift
This PR is to fix the broken images issue https://github.com/XCTestHTMLReport/XCTestHTMLReport/issues/274.
- Use `relativeUrl` to construct the return value in `ResultFile.exportPayload(id:, fileName:)`
- Add unit tests to avoid being broken in the future
> Fix: Use relative path for attachment reference in HTML report

- Tests/XCTestHTMLReportTests/CliTests.swift
Retroactively addressing comments from #281 - ensuring that linked attachments use a correct relative URL
> Fix attachment test relative path assertion

- Sources/XCTestHTMLReportCore/Classes/Models/JUnitReport.swift
- Tests/XCTestHTMLReportTests/CoreTests.swift
- Tests/XCTestHTMLReportTests/JUnitReportTests.swift
- Tests/XCTestHTMLReportTests/SanityTests.swift
- XCTestHTMLReportSampleApp/SampleAppUITests/RetryTests.swift
👋 
This PR introduces the `system-err` XML tag for the junit report. You can see how this is used by the teamcity junit parser [here](https://github.com/JetBrains/teamcity-xml-tests-reporting/blob/b86b9336679a04653792b2915af8de4941304c75/agent/src/jetbrains/buildServer/xmlReportPlugin/parsers/antJUnit/AntJUnitXmlReportParser.java#L145).
This way, now when there are multiple iterations of a test, the final result of the test is the status of its last iteration. For example, having two iterations:
* If the first succeeds, test is shown as passed
* If the first fails and the second succeeds, test is shown as passed
* If both fail, test is shown as failed
Failed iterations that are not the last one are reported using the `system-err` tag.
I would say this makes more sense than previous …
> Report mixed tests as success in junit if the last iteration passed

- Tests/XCTestHTMLReportTests/CoreTests.swift
- Tests/XCTestHTMLReportTests/SanityTests.swift
SanityTests are reserved for tests using a lightweight bundle - suitable for on-the-fly integration testing in environments such as Brew.
We'll move extraneous tests to a more appropriate test class/file.
Also slightly adjust assertions for Junit device info to accommodate builder changes. In this case, the test fails on Xcode 14 since the default simulator version changes.
> move tests out of sanity

- Package.resolved
- Package.swift
- Sources/XCTestHTMLReport/XCTestHtmlReport.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Activity.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Iteration.swift
- Sources/XCTestHTMLReportCore/Classes/Models/ResultFile.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Summary.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Test.swift
- Sources/XCTestHTMLReportCore/Classes/Protocols/EmittableOutput.swift
Background
Updating the forked XCResultKit dependency to a rebased commit. This includes the Xcode 14 schema updates from the upstream repo as well as the encodable capability to output a nested json object from the invocation record.
Changes
- Update XCResultKit sha
- Minor refactors to reflect updated schema
- Add `--json` flag to output a `report.json` file containing the nested xcresult json data
> Update XCResultKit, add --json report flag

- .github/workflows/ci.yml
- .github/workflows/release.yml
Background:
Multiple `--arch` flags appears to be no longer supported in Swift 5.7 (?). Instead outputting `error: duplicate key found: '<ResolvedTarget: CommandLineTool>'`.
Changes:
- Modify CI script use the `--triple` specifier to build multi-arch
- Update Release (rename file) and lipo into a single fat binary
> make fat binary

- Sources/XCTestHTMLReport/XCTestHtmlReport.swift
AsyncParsableCommand doesn't work with `@main` on Swift 5.5 and below. Since we're not currently using async functionality in the main method this can be removed.
> Remove AsyncParsableCommand

- Package.swift
Update to latest forked commit of XCResultKit to incorporate better date formatting when generating recursive json.
https://github.com/tylervick/XCResultKit/commit/d5462510fc09055594b3cf472e443bee0d130043
> update XCResultKit sha for dateEncodingStrategy fix

- Sources/XCTestHTMLReportCore/Classes/HTMLTemplates.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Attachment.swift
- Sources/XCTestHTMLReportCore/HTML/gif.html
At Trendyol, we have implementation which takes a screenshot every 3 seconds in test cases and creates a gif from that screenshots. We add gif as an attachment so we want to overview the failed cases with using that gifs.
This pr adds gif support for animating the gif when attachment is clicked.
> Added gif attachment type support

- Sources/XCTestHTMLReportCore/HTML/screenshot.html
All screenshots are loaded immediately when opening the report even if they aren't in view. When opening a large report hosted remotely containing thousands of screenshots it can take several minutes to load. A quick fix is to [enable native image lazy loading](https://web.dev/articles/browser-level-image-lazy-loading) which is [supported in most popular browsers](https://caniuse.com/loading-lazy-attr) today.
> Lazy load screenshots

- Sources/XCTestHTMLReportCore/Classes/Models/Run.swift
Closes https://github.com/XCTestHTMLReport/XCTestHTMLReport/issues/333
This PR adds parallel test processing by utilising a simple `OperationQueue`. 
The concurrent operation count is set twice the time of the available CPU cores. As far as I know the `OperationQueue` has some internal max limits and so it is not too much of a problem if we set a higher value. 
Also the the final array has to be sorted because of the order will be random for every html generation because of the multithreading.
> Add parallel test processing

- Package.resolved
- Package.swift
Bumping XCResultKit dependency after Xcode 15/xcresulttool 3.44 schema updates: https://github.com/davidahouse/XCResultKit/pull/50
We're still using the forked version to support JSON output, but once https://github.com/davidahouse/XCResultKit/pull/46 is merged we can switch back to the original repo.
> bump xcresultkit to use xcresulttool version 3.44

- Sources/XCTestHTMLReportCore/Classes/HTMLTemplates.swift
- Sources/XCTestHTMLReportCore/Classes/Models/TestScreenshotFlow.swift
- Sources/XCTestHTMLReportCore/HTML/gif.html
- Sources/XCTestHTMLReportCore/HTML/index.html
- Sources/XCTestHTMLReportCore/HTML/run.html
- Sources/XCTestHTMLReportCore/HTML/screenshot.html
This is an improvement on my [previous change](https://github.com/XCTestHTMLReport/XCTestHTMLReport/pull/339 ) to lazy load screenshots. We were still seeing some images load on initial page load and realized there are other types I could include.
This is a huge performance improvement in my testing. We have a gigantic report that would freeze the browser for 30 seconds and now loads in seconds. Confirmed in network traffic only the main HTML file is downloaded until you start manually expanding sections.
> Lazy load video and everything else

- .gitignore
- Sources/XCTestHTMLReportCore/Classes/HTMLTemplates.swift
- Sources/XCTestHTMLReportCore/Classes/Models/Test.swift
In the latest Xcode build tools [15.1](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_1-release-notes) and iOS 17.0.1 versions we've been randomly getting some "dangling" test data, meaning they are in a test group a level higher than they should be. This causes the HTML report tool to end early resulting in many missing tests because it assumes since there is a child test there can't be a child test group.
This changes handles the bad data better by checking all children regardless of their type. We'll reach out to Apple support to see if they are already aware of the issue but for now this unblocks us.
I ran the unit tests and manually ran reports on known good and bad data. There is no difference to users not experiencing the issue.
> Support mixed children test types in test suites

- Package.resolved
- Package.swift
This is to address [#358] issue. 
The [davidahouse/XCResultKit.git](https://github.com/davidahouse/XCResultKit) already has the patch to resolve Xcode16 schema changes. I am just replacing the existing XCResultKit source with this one. 
Here's a sample report file generated from TestResults.xcresult
[report.json](https://github.com/user-attachments/files/16477024/report.json)
> Update source for XCResultKit to support Xcode16 schema changes

- Sources/XCTestHTMLReportCore/Classes/Models/JUnitReport.swift
- Tests/XCTestHTMLReportTests/CoreTests.swift
- Tests/XCTestHTMLReportTests/JUnitReportTests.swift
- XCTestHTMLReportSampleApp/SampleAppUITests/RetryTests.swift
👋 
Handle successful test with failed assertions during Junit report generation. See code for details.
Context: I experienced the edge case of a test with a failed assertion, but success status:
> Handle successful test with failed assertions during Junit report generation

- Sources/XCTestHTMLReportCore/Classes/Models/Activity.swift
Initialization of an attachment is now inside an autoreleasepool because the memory footprint is huge when using the -z option. The memory usage jumps to 10 gigabytes under 10 seconds. Releasing the NSImage related objects at each iteration via autorelease pool reduces it to a few hundred megabytes.
> Reduce the memory footprint when -z option is used
