XCUITestHTMLReport/XCUITestHTMLReport.xcodeproj/project.pbxproj, XCUITestHTMLReport/XCUITestHTMLReport/Extensions/TimeInterval+Time.swift, XCUITestHTMLReport/XCUITestHTMLReport/HTML/activity.html, XCUITestHTMLReport/XCUITestHTMLReport/HTML/test.html, XCUITestHTMLReport/XCUITestHTMLReport/HTMLTemplates.swift, XCUITestHTMLReport/XCUITestHTMLReport/Models/Activity.swift, XCUITestHTMLReport/XCUITestHTMLReport/Models/Test.swift
=> Display activity and test duration in hms

XCUITestHTMLReport/XCUITestHTMLReport/Models/Test.swift
=> Added amount of tests

XCUITestHTMLReport/XCUITestHTMLReport/main.swift
=> Print version

XCUITestHTMLReport/XCUITestHTMLReport/HTML/index.html, XCUITestHTMLReport/XCUITestHTMLReport/HTMLTemplates.swift
=> 36/37: Impossible to copy with Cmd + C and searching with Cmd + f

XCTestHTMLReport/XCTestHTMLReport.xcodeproj/xcshareddata/xcschemes/XCTestHTMLReport.xcscheme, XCTestHTMLReport/XCTestHTMLReport/HTML/run.html, XCTestHTMLReport/XCTestHTMLReport/HTMLTemplates.swift, XCTestHTMLReport/XCTestHTMLReport/Models/Run.swift, XCTestHTMLReport/XCTestHTMLReport/Models/Test.swift
#46 
Added the number of:
- all tests
- all failed tests
- all passed tests
in the tool bar above the tests
=> #46: Added number All/Passed/Failed tests in toolbar

XCTestHTMLReport/XCTestHTMLReport.xcodeproj/xcshareddata/xcschemes/XCTestHTMLReport.xcscheme, XCTestHTMLReport/XCTestHTMLReport/HTML/index.html, XCTestHTMLReport/XCTestHTMLReport/HTMLTemplates.swift
=> 52: Fixed: Tests not scrolling on Firefox

install.sh
=> Fix install script

XCTestHTMLReport/XCTestHTMLReport/Classes/HTMLTemplates.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Activity.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Attachment.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Run.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Summary.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Test.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/TestSummary.swift, XCTestHTMLReport/XCTestHTMLReport/HTML/screenshot.html
=> Fixed: Wrong screenshot path for secondary reports

README.md
=> Fix homebrew formula

XCTestHTMLReport/XCTestHTMLReport/Classes/Models/TestSummary.swift, install.sh
=> 94 xctesthtmlreport hanging

XCTestHTMLReport/XCTestHTMLReport.xcodeproj/xcshareddata/xcschemes/XCTestHTMLReport.xcscheme, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Run.swift, tasks/test.thor
=> Fixed: use of absolute paths for screenshots

XCTestHTMLReport/XCTestHTMLReport/Classes/Models/Run.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/RunDestination.swift, XCTestHTMLReport/XCTestHTMLReport/Classes/Models/TargetDevice.swift, tasks/test.thor
=> 102 running twice same device

Sources/XCTestHTMLReport/HTML/index.html
Google chrome scrolling not working for large files.
=> Google chrome scrolling not working for large file

Sources/XCTestHTMLReport/main.swift
Changes since 2.0.0 ([compare](https://github.com/TitouanVanBelle/XCTestHTMLReport/compare/2.0.0...84dcbdd)):
New features:
* Support video and log file attachments #181
* Added image resizing, attachment cleanup and screenshot flows #168
* Implement "Skipped" tests, improve Junit report #172
* Make it possible to inline assets into the resulting index.html #148
Bug fixes:
* Google chrome scrolling not working for large file #160
* Update XCResultKit to 0.5.7 fixing #166 #169
* Support path with spaces #165 
* Fix crash in XCResultKit: XCResultKit updated #157
* Fix Homebrew for 2.0.0 release #144
Misc:
* Bump nokogiri from 1.10.4 to 1.10.8 #167
* Bump nokogiri from 1.8.5 to 1.10.4 #140
@TitouanVanBelle @nacho4d Let me know if I've missed anything. Once this is merged I'll tag a new …
=> Release 2.1.0

xchtmlreport.rb
The only thing missed in https://github.com/TitouanVanBelle/XCTestHTMLReport/pull/189
=> Bump to 2.1.0 for brew install

.github/workflows/ci.yml
=> Fix github actions CI

.github/workflows/cd.yml, Gemfile.lock, Package.swift, Sources/XCTestHTMLReport/main.swift, Sources/XCTestHTMLReportCore/Classes/Helpers/ImageHelpers.swift, Sources/XCTestHTMLReportCore/Classes/Models/Activity.swift, Sources/XCTestHTMLReportCore/Classes/Models/Attachment.swift, Sources/XCTestHTMLReportCore/Classes/Models/Iteration.swift, Sources/XCTestHTMLReportCore/Classes/Models/ResultFile.swift, Sources/XCTestHTMLReportCore/Classes/Models/Run.swift, Sources/XCTestHTMLReportCore/Classes/Models/Summary.swift, Sources/XCTestHTMLReportCore/Classes/Models/Test.swift, Sources/XCTestHTMLReportCore/Classes/Models/TestSummary.swift, Tests/XCTestHTMLReportTests/SummaryTests.swift
=> Update next from main, resolve conflicts

Sources/XCTestHTMLReport/main.swift, Sources/XCTestHTMLReportCore/Classes/Models/JUnitReport.swift, Sources/XCTestHTMLReportCore/Classes/Models/Summary.swift, Sources/XCTestHTMLReportCore/Classes/Protocols/JUnitRepresentable.swift, Tests/XCTestHTMLReportTests/CliTests.swift, Tests/XCTestHTMLReportTests/JUnitReportTests.swift, Tests/XCTestHTMLReportTests/SanityTests.swift, Tests/XCTestHTMLReportTests/TestSupport.swift
Hi 👋 
This PR is an implementation of the discussions in https://github.com/XCTestHTMLReport/XCTestHTMLReport/pull/115
=> Allow to remove device information from junit report

Sources/XCTestHTMLReport/Version.swift, Sources/XCTestHTMLReport/main.swift
Move the version string var from `main.swift` into to a standalone file for easier updating via CI.
=> extract version into Version.swift

.gitignore, Sources/XCTestHTMLReport/XCTestHtmlReport.swift, Sources/XCTestHTMLReportCore/HTML/gif.html, Sources/XCTestHTMLReportCore/HTML/index.html, Sources/XCTestHTMLReportCore/HTML/run.html, Sources/XCTestHTMLReportCore/HTML/screenshot.html, Tests/XCTestHTMLReportTests/CoreTests.swift, Tests/XCTestHTMLReportTests/TestSupport.swift, XCTestHTMLReportSampleApp/SampleAppUITests/ThirdSuite.swift
https://sonarcloud.io/project/issues?resolved=false&id=XCTestHTMLReport_XCTestHTMLReport
=> fix outstanding sonar issues

README.md
Hello! thank you for making great library. 
I want to add a guide for making json result.
It's not hard to find out the flag for making json result, but there is no guide except the helping message in terminal.
=> Update readme to add guide for json flag

Package.resolved, Package.swift, Sources/XCTestHTMLReportCore/Classes/Models/Test.swift
=> Performance optimizations
